openai:
  api_key: '${OPENAI_API_KEY}'
  model: 'gpt-5-mini-2025-08-07'
anthropic:
  api_key: '${CLAUDE_API_KEY}'
  model: 'claude-sonnet-5'
openrouter:
  api_key: '${OPEN_ROUTER}'
  model: 'openai/gpt-4.1-mini'
  url: 'https://openrouter.ai/api/v1'
ollama:
  url: 'http://localhost:11434'
  model: 'llama3.2'
  timeout: '600'

provider:
  default: 'openai'